// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ommyhzppnvzkybullnhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tbXloenBwbnZ6a3lidWxsbmhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDI1MjEsImV4cCI6MjA2Njg3ODUyMX0.oJt4vaF3POxtwCH_Jsg_HY5n2iexfJt7eIkW3d2rZwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});